# The name of the application (no spaces)
app_name: nas_species

# A brief description of the app.
description : Filter documents that contain strings related to species of interest and drop into a text file.

# Your first and last name
user: Daniel Wieferich

# Your email
email: dwieferich@usgs.gov

# The primary language the application is written in - will be used for installing dependencies
# Current options are Python, R, and Go
language: Python

# You can choose to specify a list of dictionaries, a list of terms, or both.
# If both dictionaries and terms are provided, all terms in the dictionary PLUS
# all listed terms will be used
dictionaries: [instruments]

terms: [theremin]
